---
- name: Create users on the servers
  hosts: localhost
  connection: local
    # vars:
    # user: infra
  tasks:
    - name: Add user "{{ user }}" 
      user:
        name: "{{ user }}"
        state: present
        groups: wheel

    - name: create a file in home directory
      ansible.builtin.file:
        path: "/home/{{ user }}/test"
        state: present
        
