---
- name: Test connectivity of the servers
  hosts: all
  tasks:
    - name: Ping test 
      ping:
      register: result
    
    - name: Display result
      debug:
        msg: "Check for pong"
        var: result
