---
- name: Provision VM from Template with FQDN
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Deploy VM from Template
      vmware.vmware_rest.vcenter_vm:
        name: "{{ vm_name }}"
        guest_OS: "{{ guest_os }}"
        placement:
          cluster: "{{ cluster }}"
            #  datacenter: "{{ datacenter }}"
          folder: "{{ vm_folder }}"
          resource_pool: "{{ resource_pool }}"
            # zone: "{{ zone | default(omit) }}"
          datastore: "{{ datastore }}"
        memory:
          hot_add_enabled: true
          size_MiB: "{{ memory_size }}"
        cpu: "{{ cpu_count }}"
        disks:
          - type: "thin"
            datastore: "{{ datastore }}"
            value: "{{ disk_size }}"
        nics:
          - network: "{{ network_name }}"
            start_connected: true
        source:
          type: "template"
          name: "{{ template_name }}"
        power_on: true
      delegate_to: localhost

    #- name: Set VM FQDN and Domain
     # vmware.vmware_rest.vcenter_vm_guest_identity:
      #  vm: "{{ vm_name }}"
       # host_name: "{{ hostname }}"
        #domain_name: "{{ domain }}"
      #delegate_to: localhost

