---
- name: Test vSphere Connection using AAP Credentials
  hosts: localhost
  gather_facts: no
    #collections:
    #- vmware.vmware_rest
  vars_files:
    - secret.yml
  tasks:
    - name: List Datacenters
      vmware.vmware_rest.vcenter_datacenter_info:
      register: datacenters

    - name: Print Datacenter Names
      debug:
        msg: "{{ datacenters.value | map(attribute='name') | list }}"

    - name: List of all the clusters
      vmware.vmware_rest.vcenter_cluster_info:
      register: cluster_info

    - name: Print cluster info
      debug:
        var: cluster_info

    - name: Retrieve details about the first cluster
      vmware.vmware_rest.vcenter_cluster_info:
        cluster: '{{ cluster_info.value[0].cluster }}'
      register: my_cluster_info

    - name: Gather guest vm info
      vmware.vmware.guest_info:
        guest_name: "pc-rhel8-sat"

    - name: Get the dvswitch called my-portgroup
      vmware.vmware_rest.vcenter_network_info:
        filter_types: DISTRIBUTED_PORTGROUP
        #filter_names: my portrgoup
      register: my_portgroup

    - name: Print cluster info
      debug:
        var: my_portgroup

    - name: Get VM ID
      vmware.vmware_rest.vcenter_vm_info:
        #names: 
          # - "{{ vm_name }}"
        vm: vm-2009
      register: vm_info

    - name: Print ID
      debug:
        var: vm_info.value.identity.instance_uuid

    - name: Print secret
      debug:
        msg: "Password is {{ password }}"

        
    # - name: Deploy Windows Server 2022 VM from a Template
    #   vmware.vmware.deploy_folder_template:
    #     #hostname: "10.100.151.9"
    #     #username: "pankaj@ukteam.lab"
    #     #password: "P@nkaj123"
    #     #validate_certs: false
    #     datacenter: "UKDatacenter"
    #     cluster: "UKCluster"   # Cluster where vm should be deployed
    #       #resource_pool: "{{ resource_pool | default(omit) }}"
    #     vm_folder: "Pankaj"  # The folder into which vm should be deployed
    #     template_name: "pc-ubuntu"
    #       #template_folder: "{{ template_folder }}"
    #     vm_name: "pc-ubuntu-test"
    #     datastore: "datastore2"
    #   #register: vm_info
    #   delegate_to: localhost

    
