---
- name: Test vSphere Connection using AAP Credentials
  hosts: localhost
  gather_facts: no
    #collections:
    #- vmware.vmware_rest

  tasks:
    - name: List Datacenters
      vmware.vmware_rest.vcenter_datacenter_info:
      register: datacenters

    - name: Print Datacenter Names
      debug:
        msg: "{{ datacenters.value | map(attribute='name') | list }}"

    - name: Build a list of all the clusters
      vmware.vmware_rest.vcenter_cluster_info:
      register: all_the_clusters

    - name: Retrieve details about the first cluster
      vmware.vmware_rest.vcenter_cluster_info:
        cluster: '{{ all_the_clusters.value[0].cluster }}'
      register: my_cluster_info

    - name: Print cluster name
      debug:
        var: my_cluster_info
