---
- name: Capture User Inputs for VM Provisioning
  hosts: localhost
  gather_facts: no
  vars:
    datacenter: "{{ datacenter | default('') }}"
    cluster: "{{ cluster | default('') }}"
    vm_name: "{{ vm_name | default('') }}"
    template_name: "{{ template_name | default('') }}"
    vm_folder: "{{ vm_folder | default('') }}"
    datastore: "{{ datastore | default('') }}"
    network_name: "{{ network_name | default('') }}"
    cpu_count: "{{ cpu_count | default(2) }}"
    memory_size: "{{ memory_size | default(4096) }}"
    
  tasks:
    - name: Display the provided VM details
      debug:
        msg: 
          - Datacenter: "{{ datacenter }}"
          - Cluster: "{{ cluster }}"
          - VM Name: "{{ vm_name }}"
          - Template: "{{ template_name }}"
          - Folder: "{{ vm_folder }}"
          - Datastore: "{{ datastore }}"
          - Network: "{{ network_name }}"
          - CPU Count: "{{ cpu_count }}"
          - Memory Size (MB): "{{ memory_size }}"

