---
- name: Test vSphere Connection using AAP Credentials
  hosts: localhost
  gather_facts: no
    #collections:
    #- vmware.vmware_rest
  # vars_files:
  #   - secret.yaml
  tasks:
    - name: List Datacenters
      vmware.vmware_rest.vcenter_datacenter_info:
      register: datacenters

    - name: Print Datacenter Names
      debug:
        msg: "{{ datacenters.value | map(attribute='name') | list }}"

    - name: Print Datacenter details
      debug:
        var: datacenters

    - name: List of all the datastores
      vmware.vmware_rest.vcenter_datastore_info:
      register: datastore_info

    - name: List of all the clusters
      vmware.vmware_rest.vcenter_cluster_info:
      register: cluster_info

    - name: Print cluster info
      debug:
        var: cluster_info

    - name: Retrieve details about the first cluster
      vmware.vmware_rest.vcenter_cluster_info:
        cluster: '{{ cluster_info.value[0].cluster }}'
      register: my_cluster_info

    - name: Get the dvswitch details
      vmware.vmware_rest.vcenter_network_info:
        filter_types: DISTRIBUTED_PORTGROUP
        #filter_names: my portrgoup
      register: my_portgroup

    - name: Print network info
      debug:
        var: my_portgroup

    - name: Look up the VM in the inventory
      vmware.vmware_rest.vcenter_vm_info:
        filter_names: 
        - "pc-rhel9-aap2.5-controller"
      register: vm_info

    - name: Collect information about a VM 
      vmware.vmware_rest.vcenter_vm_info:
        vm: "{{ vm_info.value[0].vm }}"
      register: vm_details
  

    - name: Print ID
      debug:
        var: vm_details.value.identity.instance_uuid

    - name: Get guest networking info
      vmware.vmware_rest.vcenter_vm_guest_networking_info:
        vm: "{{ vm_details.id }}"
      register: guest_network_info

    - name: Get guest network interface info
      vmware.vmware_rest.vcenter_vm_guest_networking_interfaces_info:
        vm: "{{ vm_details.id }}"
      register: guest_network_interface_info

        
    # - name: Deploy Windows Server 2022 VM from a Template
    #   vmware.vmware.deploy_folder_template:
    #     #hostname: "10.100.151.9"
    #     #username: "pankaj@ukteam.lab"
    #     #password: "P@nkaj123"
    #     #validate_certs: false
    #     datacenter: "UKDatacenter"
    #     cluster: "UKCluster"   # Cluster where vm should be deployed
    #       #resource_pool: "{{ resource_pool | default(omit) }}"
    #     vm_folder: "Pankaj"  # The folder into which vm should be deployed
    #     template_name: "pc-ubuntu"
    #       #template_folder: "{{ template_folder }}"
    #     vm_name: "pc-ubuntu-test"
    #     datastore: "datastore2"
    #   #register: vm_info
    #   delegate_to: localhost

    
