---
- name: Provision Windows Server 2022 VM from Template
  hosts: localhost
  gather_facts: no
  collections:
    - vmware.vmware

  tasks:
    - name: Deploy Windows Server 2022 VM from a Template
      vmware.vmware.deploy_folder_template:
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"   # Cluster where vm should be deployed
        resource_pool: "{{ resource_pool | default(omit) }}"
        vm_folder: "{{ vm_folder }}"  # The folder into which vm should be deployed
        template_name: "{{ template_name }}"
        template_folder: "{{ template_folder }}"
        vm_name: "{{ vm_name }}"
        datastore: "{{ datastore }}"
      #register: vm_info
      delegate_to: localhost

    - name: Look up the details of the newly provisioned VM
      vmware.vmware_rest.vcenter_vm_info:
        filter_names: 
          - "{{ vm_name }}"
      register: vm_details

    #- name: Collect information about a specific VM
     # vmware.vmware_rest.vcenter_vm_info:
      #  vm: '{{ vm_details.value[0].vm }}'
     # register: vm_info

    - name: Set CPU configuration
      vmware.vmware_rest.vcenter_vm_hardware_cpu:
        vm: "{{ vm_details.value[0].vm }}"
        count: "{{ cpu_count }}"
        cores_per_socket: "{{ cores_per_socket }}"
      delegate_to: localhost

    - name: Set Memory Configuration
      vmware.vmware_rest.vcenter_vm_hardware_memory:
        vm: "{{ vm_details.value[0].vm }}"
        size_MiB: "{{ memory_size }}"
      delegate_to: localhost

    - name: Add Additional Disk
      vmware.vmware_rest.vcenter_vm_hardware_disk:
        vm: "{{ vm_details.value[0].vm }}"
        new_vmdk:
          type: "thin"
          capacity: "{{ disk_size }}"
      delegate_to: localhost

    - name: Configure Network Interface
      vmware.vmware_rest.vcenter_vm_hardware_ethernet:
        vm: "{{ vm_details.value[0].vm }}"
        nics:
          - type: "VMXNET3"
            backing:
              type: "STANDARD_PORTGROUP"
              network_name: "{{ network_name }}"
            state: "CONNECTED"
      delegate_to: localhost
