---
- name: Provision VM from Template
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Deploy a VM 
      vmware.vmware_rest.vcenter_vm:
        name: "{{ vm_name }}"
        guest_OS: "{{ guest_os }}"
        placement:
          cluster: "{{ cluster }}"
          folder: "{{ vm_folder }}"
          resource_pool: "{{ resource_pool }}"
          datastore: "{{ datastore }}"
        memory:
          hot_add_enabled: true
          size_MiB: "{{ memory_size }}"
        cpu: 
          count: "{{ cpu_count }}"
        disks:
          - type: "thin"
            datastore: "{{ datastore }}"
            value: "{{ disk_size }}"
        nics:
          - network: "{{ network_name }}"
            start_connected: true
        power_on: true
      

    - name: List Local Content Library
      vmware.vmware_rest.content_locallibrary_info:
      register: content_library

    - name: Print Library info
      debug:
        var: content_library

